services:
  - type: web
    name: rag-chatbot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION
        value: rag_chatbot_docs
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
